Changing in dev branch...updating this line in dev branch deploy file.....updating this file again...
changing in master branch......First line updating again...
updating this line in dev branch deploy file
Today update...
today is friday.....
Updated code in dev branch..
Today update...
Merge conflicts should occur..
ok..
