Updated in stage branch to demonstarte the PR...
Hello this file contains the deployment script...
I'm just updating this file here
updating this line in dev branch deploy file
update deploy in master..
